### ISSUE TITLE
Typo in download_flan_2022.sh and instruction_tuning.sh

### ISSUE THREAD

**Issue by Linxi-ZHAO** [yegcjs/DiffusionLLM#1]
I came across a couple of typos in the download_flan_2022.sh and instruction_tuning.sh scripts. Should be a simple fix.

1.revise `mkir` to `mkdir`
https://github.com/yegcjs/DiffusionLLM/blob/ff157e91f10a58f12cc53400db0fcc55c4cb915c/scripts/download_flan_2022.sh#L1
2. revise  `--steps` to `--train_steps` to accord with command in README
https://github.com/yegcjs/DiffusionLLM/blob/ff157e91f10a58f12cc53400db0fcc55c4cb915c/scripts/instruction_tuning.sh#L17

**Comment by yegcjs** [comment]
Thank you for kindly pointing out this! We have made an update to revise these typos.
