### ISSUE TITLE
Unable to access model checkpoints

### ISSUE THREAD

**Issue by PinzhengWang322** [yegcjs/DiffusionLLM#2]
Thanks for your great work!
I have encountered an issue when trying to access the model checkpoints. 
The links provided in the README.md file show "This file does not exist". 
Could you please look into this and update these links?

**Comment by poonehmousavi** [comment]
I have the same problem, any updates on that?

**Comment by Utkarsh4430** [comment]
Same issues

**Comment by yegcjs** [comment]
Sorry for the issue.

We have recently updated the download link for the checkpoints.
Please check the latest README.
